version: '3.8'
services:
  couchbase:
    build: .
    ports:
      - "8091:8091"  # Couchbase Web Console
      - "8092:8092"  # Query service
      - "8093:8093"  # Index service
      - "8094:8094"  # Full Text Search
      - "11210:11210" # Data service
    volumes:
      - couchbase_data:/opt/couchbase/var

volumes:
  couchbase_data: